project:
  type: website
  output-dir: docs


website:
  title: "Minimal Quarto Lab Book"
  sidebar:
    smooth-scroll: true
    logo: img/logo.png
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - index.qmd
      - text: "Main Code"
        collapse: true
        contents:
          - main_code_text.qmd
          - analysis_text.qmd
      - week1.qmd
      - week2.qmd
      - week3.qmd



format:
  html:
    theme: lumen
    highlight-style: pygments
    
    grid:
      sidebar-width: 305px
    toc: true
    chapters-folding: true
    number-chapters: true
    number-sections: false

    
