project:
  type: website
  output-dir: docs


website:
  title: "Minimal Quarto Lab Book"
  sidebar:
    smooth-scroll: true
    logo: img/logo.png
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - index.qmd
      - week1.qmd
      - notebook.ipynb
      - week2.qmd
      



format:
  html:
    theme: lumen
    highlight-style: pygments
    
    grid:
      sidebar-width: 305px
    toc: true
    chapters-folding: true
    number-chapters: true
    number-sections: false

    
