
# Lab book in Quarto

Quarto is a an editing platform centered on Markdown.

You can write down multiple kinds of interactive documents in Quarto, including websites that mix code, text, equations etc. The individual notebook can be jupyter notebooks or dedicated markdown documents.

Combined with combined repositories such as GitHub, Quarto allows you to create a static website to collect your progress is very easily.

For more information on Quarto, see [https://quarto.org](https://quarto.org)

## What you need 


- A `quarto` installation, e.g. from  [https://quarto.org](https://quarto.org)
- A suitable editor (e.g. VSCode)
- An account on Github (or similar services)
- Some knowledge of `git`



## To create your website on github

- Go to your repository on github (e.g. https://github.com/FTurci/minimal-quarto-lab-book)
- Click on `Settings`
- Click on `Pages` on the left sidebar
- Under the section **Branch** select branch `main` and select folder `docs`
- Commit and push your changes and you are done.
